[package]
name = "cansimple"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
defmt = { version = "1.0.1", optional = true }
embedded-can = "0.4.1"

[features]
defmt-1 = ["dep:defmt"]
